export function formatCurrency(amount: number, currency = 'KES'): string {
  return new Intl.NumberFormat('en-KE', {
    style: 'currency',
    currency,
    minimumFractionDigits: 0,
    maximumFractionDigits: 0,
  }).format(amount);
}

export function generateWhatsAppMessage(project: any): string {
  const total = formatCurrency(Number(project.total || 0));
  const validUntil = project.validUntil 
    ? new Date(project.validUntil).toLocaleDateString('en-KE')
    : '30 days';

  const message = [
    `Dear ${project.clientName || 'Client'},`,
    '',
    `Please find your project estimate below:`,
    `📋  Project: ${project.name}`,
    `📍  Location: ${project.location || 'Not specified'}`,
    `💰  Estimated Total: ${total}`,
    `   (Incl. labour, contingency, profit)`,
    `📅  Valid until: ${validUntil}`,
    '',
    `View full BOQ and approve here:`,
    `${project.shareUrl || 'Link to client portal'}`,
    '',
    `Generated by EngiQuote KE`,
  ].join('\n');

  return message;
}

export function openWhatsAppShare(phone: string, message: string): void {
  const encodedMessage = encodeURIComponent(message);
  const url = `https://wa.me/${phone.replace(/^0/, '254')}?text=${encodedMessage}`;
  window.open(url, '_blank');
}

export function generateShareableLink(token: string, baseUrl?: string): string {
  const base = baseUrl || window.location.origin;
  return `${base}/portal/shared/${token}`;
}